### ISSUE TITLE
[FEATURE] <Remove underline when user hover on About button>

### ISSUE THREAD

**Issue by shivam-sharma7** [kubesimplify/website#101]
### Description

- Remove underline when user hover on About button. it's not good to see.

### Screenshots

 
![Screenshot (132)_LI](https://user-images.githubusercontent.com/91419219/175214233-cb274617-c571-4487-afbb-66eb3358d3ed.jpg)

### Additional information

using this css property we can remove it.
- text-decoration: none;

**Comment by Jai-Solania-29** [comment]
Hey I want to work upon this issue. 😃

**Comment by Hat52** [comment]
Anyone working on this or can I work ont it?

**Comment by bhavyastar** [comment]
Hey @Jai-Solania-29 and @Hat52, someone has already made PR for this issue. Thanks for asking! You both can work on other issues. :)
