### ISSUE TITLE
Footer is not Responsive

### ISSUE THREAD

**Issue by Jai-Solania-29** [kubesimplify/website#102]
### Description

Footer looks perfect only on the default desktop view, but if we change the dimension of the website then the footer is getting disbalanced.

### Screenshots

![image](https://user-images.githubusercontent.com/90816300/175312476-820e62a6-e76f-421b-90ce-3e4c8bf629cd.png)

**Comment by AvineshTripathi** [comment]
Must be because of new merge https://github.com/kubesimplify/website/pull/51

**Comment by bhavyastar** [comment]
You can start working on this. If you need any help then please feel free to ask.😀 
@Jai-Solania-29

**Comment by Jai-Solania-29** [comment]
Thank you @bhavyastar 😃

**Comment by bhavyastar** [comment]
Hey @Jai-Solania-29 , If you need any help, feel free to tag me in the KubeSimplify discord, I would be happy to help!

**Comment by Jai-Solania-29** [comment]
Ok sure @bhavyastar 😃

**Comment by Jai-Solania-29** [comment]
Yes, @bhavyastar I'm still working on this, and I'll push my changes in a few days.

**Comment by AvineshTripathi** [comment]
This issue is resolved with recent merges #121
