### ISSUE TITLE
[FEATURE] Add remaining part of homepage

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#103]
## some pointers
- We have the code ready but that is not combined with website repo 
- It uses bootstrap which we are currently not using so if bootstrap makes the entire website smooth throughout then please do use that all across homepage 

## steps to perform 
- copy paste the provide html and css in the https://github.com/kubesimplify/website/blob/main/src/components/HomepageFeatures/index.js
- see if we can achieve similar result without using bootstrap(the code provided uses bootstrap)
- make everything uniform 

Additional task to perform 
Make entire page in modular form like ambassador page 

### Additional information

I can send you the code for html and css, join our discord https://discord.gg/nNTaHn82 and say a hi

**Comment by verma-kunal** [comment]
Assigning @bhavyastar to work on this!

**Comment by bhavyastar** [comment]
Yes, Happy to work on that!
