### ISSUE TITLE
[Bug] Making pages responsive 

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#105]
### Description

Currently the pages are not properly responsive to different screen sizes and devices
The aim of the issue is to research and implement uniform responsiveness through out the website 

### Additional information

Possible solution to this would be using some libraries like `react-responsive` or `@media` css
P.S. your suggestions are always welcome

**Comment by Brijrajsinh01** [comment]
I will be working on it.

**Comment by mayankkuamr001** [comment]
Assign this to me as well
