### ISSUE TITLE
[FEATURE] Link "Workshops" navigation

### ISSUE THREAD

**Issue by OmAximani0** [kubesimplify/website#110]
### Description

Since [Kubesimplify Live Workshops](https://kubesimplify.github.io/live-workshops/) has announced we can link that to "Workshops" in Navbar

### Screenshots

![image](https://user-images.githubusercontent.com/75031769/177391639-107b3e6e-e77e-4fcd-b327-ad0c1e6e484a.png)

**Comment by shivam-sharma7** [comment]
can you assign me?
