### ISSUE TITLE
Bug in Newsletter

### ISSUE THREAD

**Issue by SugamKuber** [kubesimplify/website#112]
### Description

1. The Email address is not centred
2.  The button is not aligned with the  email Text box
3. The Cursor pointer events doesn't work

I can slove those if you give the issue to me

### Screenshots

![image](https://user-images.githubusercontent.com/86460476/177826189-a53d3e63-cdab-4ac5-8521-d585f693e40e.png)

**Comment by bhavyastar** [comment]
You can start working on this!

**Comment by AvineshTripathi** [comment]
Change the alignment once I integrate the newsletter with it

**Comment by AvineshTripathi** [comment]
is this issue still there or I can close this issue @SugamKuber

**Comment by error404-sp** [comment]
![Imgur](https://i.imgur.com/bnb7BAV.png)
The button still needs padding and the text box length can be increased.
@AvineshTripathi Can I work on this or any other feature that is not assigned.

**Comment by SugamKuber** [comment]
Hey, I got bit busy, I didnt do anything about it
Give the issue to someone else

**Comment by AvineshTripathi** [comment]
issue has been solved
