### ISSUE TITLE
[FEATURE] Remove buy me a coffee

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#117]
### Description

We do not need `Buy me a coffee` button in the footer so the task would be to remove the button, remove the `or` above the button and align the `sponsor` button accordingly  

### Screenshots

![2022-07-14_14-25](https://user-images.githubusercontent.com/73980067/178945010-3242fa96-85e3-4ea0-a8e0-e47ed486faaa.png)

**Comment by MJCoder15** [comment]
I think this issue is fixed i saw on website there is no "buy me a coffee" BUTTON so i think maintainers should remove this issue from issue list

**Comment by shivam-sharma7** [comment]
can i work on this issue?

**Comment by AvineshTripathi** [comment]
do  you want to workon the issue @shivam-sharma7 ?

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
**Now, What should I do?**

**Comment by shivam-sharma7** [comment]
> **Now, What should I do?**
check website- https://kubesimplify.github.io/website/, I think this is already solved.

**Comment by AvineshTripathi** [comment]
issue is solved
