### ISSUE TITLE
[Bug] <Set the margin from  left and right of both cards >

### ISSUE THREAD

**Issue by shivam-sharma7** [kubesimplify/website#124]
### Description

- We can see extra space from both side and it's not look perfect, So reduce the extra spaces from top,right and left.You can see highlighted area following image. 

### Screenshots

![Screenshot (137)](https://user-images.githubusercontent.com/91419219/179545293-2c3bea85-4fc0-4054-a546-9ec71f470267.jpg)

**Comment by danishansari22** [comment]
Hey i can solve this problem can i do it?
