### ISSUE TITLE
[Bug] Apply Now button not working.

### ISSUE THREAD

**Issue by rakshitgondwal** [kubesimplify/website#129]
### Description

Apply button in the Kubesimplify Ambassador is not working.

### Screenshots

![Screenshot (172)](https://user-images.githubusercontent.com/98955085/180604934-ee06a92f-73fe-4f3c-8160-9ffed7326437.png)

**Comment by bishal7679** [comment]
@rakshitgondwal It is not linked yet with the ambassador form. Thats why it is not redirecting. This is not an issue for now

**Comment by rakshitgondwal** [comment]
@bishal7679 should I close this issue then?

**Comment by bishal7679** [comment]
@rakshitgondwal This issue is resolved now

**Comment by rakshitgondwal** [comment]
alright
