### ISSUE TITLE
[FEATURE] Footer section needs some space from top

### ISSUE THREAD

**Issue by bishal7679** [kubesimplify/website#135]
## Problem to be solved

Footer section looks like collapsed with kubesimplify ambassador div. 

![Screenshot (233)](https://user-images.githubusercontent.com/70086051/181576166-52080c8b-7017-40fd-b3b6-188f43ac632b.png)

## Proposed solution

It would be nice if we add some space from ambassador div section

![Screenshot (232)](https://user-images.githubusercontent.com/70086051/181576513-dda04c49-03a1-45db-a40d-dbab04f10595.png)

**Comment by abhinav2712** [comment]
I would love to work on this issue, assign me with this task, thank you

**Comment by AvineshTripathi** [comment]
I think we don't need this issue @bishal7679 

If you have something to say you can reopen
