### ISSUE TITLE
Add PR template(s)

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/website#14]
We need a PR template to guide folks for all they need to mention while making a PR.

**Comment by abh139** [comment]
Pls assign this to me

**Comment by SuperAayush** [comment]
I think @abh139 you already had this covered in the issue #6 description.

**Comment by abh139** [comment]
No that is just for Issue template, for PR we need to create another issue for easy reviewing

**Comment by AvineshTripathi** [comment]
@abh139 as soon as the PR for the issue template is merged please do a PR for PR template

**Comment by abh139** [comment]
@AvineshTripathi Sure
