### ISSUE TITLE
[FEATURE] The font size of navbar content.

### ISSUE THREAD

**Issue by Brijrajsinh01** [kubesimplify/website#151]
### Description

Here at navbar the size of texts are not consistent i.e. the font size of about is greater then learn and community. Which seems quite unsymmetrical.
I can work on it and make it better if assigned to me.

### Screenshots

![image](https://user-images.githubusercontent.com/89502887/182574978-f91a61b7-7e67-483b-9ca4-481af8141bf6.png)

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
**Now, What should I do?**

**Comment by AvineshTripathi** [comment]
hey @KetanParmar07 I think with latest merges this issue is solved so maybe you can look for other issues if not I'll help you out to find it

**Comment by AvineshTripathi** [comment]
closing this issue as it is fixed
