### ISSUE TITLE
[FEATURE] Sponsor button symmetry.

### ISSUE THREAD

**Issue by Brijrajsinh01** [kubesimplify/website#152]
### Description

The sponsor button area at the footer is quite unaligned the text and the button do not have proper space within the box. And also the $logo which is at the left can be made look more appealing within the button.
I can work on it if issue assigned to me.

### Screenshots

![image](https://user-images.githubusercontent.com/89502887/182576624-b97843fc-1a4e-45d3-9df6-58c4894e3733.png)

**Comment by bishal7679** [comment]
@Brijrajsinh01 You can start working with it

**Comment by AvineshTripathi** [comment]
Please fix all the button alignment/css present in the homepage

**Comment by AvineshTripathi** [comment]
@Brijrajsinh01 any updates?

**Comment by Brijrajsinh01** [comment]
> @Brijrajsinh01 any updates?

Prs for all the changes will be made by tonight or latest by tomorrow.

**Comment by AvineshTripathi** [comment]
issue is solved
