### ISSUE TITLE
[Bug] <Set the margin of buttons, view videos & view blogs >

### ISSUE THREAD

**Issue by shivam-sharma7** [kubesimplify/website#153]
### Description

- Set the margin of both Cards buttons- 'view videos' and 'view blogs'.
- following image you can refer to understanding problem.

### Screenshots

![Screenshot (138)](https://user-images.githubusercontent.com/91419219/182817037-703de0cd-db22-4439-92eb-cbb7c8ec6cb0.png)

**Comment by LOKESWARAN-ARULJOTHI** [comment]
Hi, I am willing to work on this bug. Can you assign it to me?

**Comment by shivam-sharma7** [comment]
> Hi, I am willing to work on this bug. Can you assign it to me?

no, But you can go for new issue.

**Comment by bishal7679** [comment]
@shivam-sharma7 I think it would be better if we give a chance to new contributor for contributing in our project as well

**Comment by bishal7679** [comment]
> Hi, I am willing to work on this bug. Can you assign it to me?

You don't need to be assigned on a particular issue. If you see that any PR has not raised yet against any issue then you can start working on that issue.
Thank You for showing interest💖

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 I think it would be better if we give a chance to new contributor for contributing in our project as well

i do, but i have made it already.

**Comment by bishal7679** [comment]
> > @shivam-sharma7 I think it would be better if we give a chance to new contributor for contributing in our project as well
> 
> i do, but i have made it already. @bishal7679

No worries at all 👍
