### ISSUE TITLE
feat: add about page for the website

### ISSUE THREAD

**Issue by bhavyastar** [kubesimplify/website#17]
Add an About page where the main purpose of kubesimplify will be there.
There are different sections like: 
1. Details about the founder.
2. Details about the team members.
3. Subscribe to newsletter
4.  Amazing footer.

**Comment by anubha-v-ardhan** [comment]
Please wait for triage being accepted before making a PR resolving this issue.
The base website needs to be setup first (see #5)

**Comment by bhavyastar** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by AvineshTripathi** [comment]
@bhavyastar any updates?
