### ISSUE TITLE
[FEATURE] Re-implement HomePage 

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#174]
### Description

We are to re implement the home page based new design 
Points to consider:
- maintain the uniformity of the code like we have for `ambassador` page and `about` page i.e. modular code
- the responsiveness should not be disturbed(don't try to hard code position cause docusaurous handles that to some extend)
- dont change the current design or implementation of navbar and footer 

### Additional information

Here is the new design: https://www.figma.com/proto/DNiw9eEdr4XWVO9i2NMtNK/Kubesimplify-Website?page-id=0%3A1&node-id=157%3A46&starting-point-node-id=157%3A46&scaling=scale-down-width&hide-ui=1

Ask for help if needed

**Comment by sanyamjain04** [comment]
I want to work on this!

**Comment by shivam-sharma7** [comment]
> I want to work on this!

@sanyamjain04 you can work on this issue, don't wait for assign.
