### ISSUE TITLE
[OTHER] Update the Contributor.md in Readme.md

### ISSUE THREAD

**Issue by nithinrajshekhar** [kubesimplify/website#189]
### What would you like to share?

Update the link for [Contribution.md](https://github.com/kubesimplify/website/blob/main/CONTRIBUTION.md) with [CONTRIBUTING.md](https://github.com/kubesimplify/website/blob/main/CONTRIBUTING.md) in README.md

**Comment by PratikDey** [comment]
Can I work on this issue?

**Comment by ryuusama09** [comment]
hi , can I work on this issue ?

**Comment by AvineshTripathi** [comment]
you can take issues without getting assigned and raise PR

**Comment by AvineshTripathi** [comment]
@PratikDey @ryuusama09 anyone willing to take this?

**Comment by PratikDey** [comment]
May I?

**Comment by codezuma** [comment]
@AvineshTripathi  is it resolved.

**Comment by AvineshTripathi** [comment]
Anyone can work on the issue and raise a PR just make sure you update in the comment that you are working

**Comment by JagveerGagaan** [comment]
I think this issue is resolved so, I would suggest closing it : )
