### ISSUE TITLE
[OTHER] We are now hosted the site at "kubesimplify.com", but the repo still shows "kubesimplify.github.io"

### ISSUE THREAD

**Issue by karnatisrinivas** [kubesimplify/website#192]
### What would you like to share?

<img width="391" alt="Screenshot 2022-09-13 at 2 00 07 PM" src="https://user-images.githubusercontent.com/52213014/189852147-c50f7ef5-d2f3-4306-b05a-a323faf26ff7.png">

We are now hosting the site at "kubesimplify.com", but the repo still shows "kubesimplify.github.io".

**Comment by shivam-sharma7** [comment]
Can i work upon it?

**Comment by AvineshTripathi** [comment]
issue fixed closing this
