### ISSUE TITLE
[Add] Guide for setting up the wesbite locally 

### ISSUE THREAD

**Issue by verma-kunal** [kubesimplify/website#20]
A proper guide on setting up the wesbite locally on a system (added to the README) would help other folks in the community to contribute

**Comment by verma-kunal** [comment]
Would be working on this one! 🙂

**Comment by anubha-v-ardhan** [comment]
This issue is already covered #1. We can use that issue as this will go on the README as well. Can I close this issue?

>Would be working on this one!

You and @abh139 can collaborate on #1 to design a README for this repo.

**Comment by verma-kunal** [comment]
> This issue is already a part of #1. We can use that issue as this will go on the README as well. Can I close this issue?
> 
> > Would be working on this one!
> 
> You and @abh139 can collaborate on #1 to design a README for this repo.

Sure, sounds good!
