### ISSUE TITLE
Unable to join the discord server.

### ISSUE THREAD

**Issue by rakshitgondwal** [kubesimplify/website#205]
### What would you like to share?

Not being able to join the discord server from the link provided on the website.

![Screenshot (297)](https://user-images.githubusercontent.com/98955085/191959241-3a613089-ffa6-4fe6-a8b4-4ac9dbb05a4e.png)

When I try to join the server from my mobile phone- 
![WhatsApp Image 2022-09-23 at 6 00 14 PM](https://user-images.githubusercontent.com/98955085/191960594-c8e593fd-6adb-480b-830d-79816987391c.jpeg)

**Comment by AvineshTripathi** [comment]
@rakshitgondwal is everything solved

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal is everything solved

Nope

**Comment by ppborah** [comment]
I faced the similar issue; I would like to work on this!
Please assign :)

**Comment by codezuma** [comment]
@ppborah are you working on this 
issue

**Comment by ppborah** [comment]
Hi @codezuma,
I was but please feel free to create a PR :)

**Comment by ppborah** [comment]
@codezuma, I think the link should direct the user to https://discord.com/invite/26Z384WSPB

**Comment by codezuma** [comment]
@ppborah but the issue isn't closed so i asked.

**Comment by ppborah** [comment]
No worries, please go ahead and create a PR :)

**Comment by rakshitgondwal** [comment]
Actually, my old account was hacked which got my IP address banned from kubesimplify's discord server. Thus, I am unable to join the server with any new account I make even after using VPN.
I guess, if I were to able to get a unban on my old account, I will be able to join then. @AvineshTripathi
