### ISSUE TITLE
[FEATURE] The size of the contents of the footer should be increased on mobile.

### ISSUE THREAD

**Issue by rakshitgondwal** [kubesimplify/website#206]
### Description

While viewing the website from a mobile phone, the size of the contents of the footer appears to be small and should be increased.

### Screenshots

<img src="https://user-images.githubusercontent.com/98955085/191961566-99aa6f7c-ea08-415e-9799-0b89dcb16cc4.jpeg" width="200">

**Comment by AvineshTripathi** [comment]
@rakshitgondwal you want to take this?

**Comment by rakshitgondwal** [comment]
Yes! I would love to work on this @AvineshTripathi
