### ISSUE TITLE
[Bug] <Fix alignment of homepage images>

### ISSUE THREAD

**Issue by shivam-sharma7** [kubesimplify/website#208]
### Description

Homepage images are not at right place. Need to fix it, for better understanding watch following screenshot.

 
 

### Screenshots

![Screenshot (178)](https://user-images.githubusercontent.com/91419219/195902844-744a05d4-3652-4808-bb7c-fd008343d76b.png)

**Comment by SohamRatnaparkhi** [comment]
Hi @shivam-sharma7, I can solve this issue. Can you assign it to me?

**Comment by shivam-sharma7** [comment]
Already opened a PR

**Comment by mayankkuamr001** [comment]
Can you please be explain about which image you are talking about. IMO all things are correct
