### ISSUE TITLE
[OTHER] Change the color of FaBars/FaTimes.

### ISSUE THREAD

**Issue by rakshitgondwal** [kubesimplify/website#214]
### What would you like to share?

The color of FaBars and FaTimes elements in the navbar during mobile view should be white for better visibility (or any other color that contrasts best with the background).

# Screenshots-
![](https://user-images.githubusercontent.com/98955085/197548741-cd92aa26-e7f1-4d0e-acb1-312c7ed4f526.png)
![](https://user-images.githubusercontent.com/98955085/197549289-8fa9a553-a93d-4b77-9fda-b8643c5f3f1b.png)

**Comment by JagveerGagaan** [comment]
I would like to work on this issue

**Comment by rakshitgondwal** [comment]
> I would like to work on this issue

Hey!! Thank you for showing interest but let's wait for this issue to be accepted first. Also, I would like to solve this issue myself. You can try working on some other issue.

**Comment by rakshitgondwal** [comment]
Hey @AvineshTripathi !! Idk why but while trying to run `npm start`, I am getting this error. Can you help me?

![](https://user-images.githubusercontent.com/98955085/201322906-771418ce-fd30-43bf-9253-be4c75339777.png)

**Comment by JagveerGagaan** [comment]
> Hey @AvineshTripathi !! Idk why but while trying to run `npm start`, I am getting this error. Can you help me?
> 
> ![](https://user-images.githubusercontent.com/98955085/201322906-771418ce-fd30-43bf-9253-be4c75339777.png)

I would suggest that you can reinstall Docusaurus and see if this helps

**Comment by rakshitgondwal** [comment]
> > Hey @AvineshTripathi !! Idk why but while trying to run `npm start`, I am getting this error. Can you help me?
> > ![](https://user-images.githubusercontent.com/98955085/201322906-771418ce-fd30-43bf-9253-be4c75339777.png)
> 
> @rakshitgondwal I would suggest that you can reinstall Docusaurus and see if this helps

I tried that but it is not working.

**Comment by AvineshTripathi** [comment]
cc @sanyamjain04 ^^^

**Comment by sanyamjain04** [comment]
Hello @rakshitgondwal, I just clone the repo and run npm install, It is working fine. 
You can try deleting package.lock.json and node modules and try `npm install`? Maybe that work.

**Comment by rakshitgondwal** [comment]
> Hello @rakshitgondwal, I just clone the repo and run npm install, It is working fine. You can try deleting package.lock.json and node modules and try `npm install`? Maybe that work.

Hey @sanyamjain04! I just figured out that I'm not able to run the website on linux (facing this issue) but it the website is running for me on windows.
