### ISSUE TITLE
[FEATURE] Back to top button

### ISSUE THREAD

**Issue by roopeshsn** [kubesimplify/website#226]
### Description

It would be great if the webpage has a "Back to top" button. And, I would like to work on this!

**Comment by aamirpatel** [comment]
This code will create a button that appears when the user scrolls down the page, and when clicked, it will take the user back to the top of the page. You can customize the button's appearance and behavior by adjusting the CSS and JavaScript code.

HTML :
<a href="#top" class="back-to-top">Back to top</a>

...

<div id="top"></div>

CSS:

.back-to-top {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 20px;
  font-size: 16px;
  background-color: #333;
  color: #fff;
  padding: 10px 20px;
  border-radius: 4px;
  cursor: pointer;
}

.back-to-top.show {
  display: block;
}


javascript:

window.addEventListener('scroll', function() {
  if (window.scrollY > 200) {
    document.querySelector('.back-to-top').classList.add('show');
  } else {
    document.querySelector('.back-to-top').classList.remove('show');
  }
});

**Comment by aamirpatel** [comment]
hey! check out this code for back to top button.

**Comment by roopeshsn** [comment]
Maintainers are not at all responsive :(

**Comment by KhushPatibandha** [comment]
Hey, I feel like I can help you with this, So can someone assign me this issue? Or should I just start working on this?

**Comment by KhushPatibandha** [comment]
@aamirpatel can you help me with what css and js files i have to make changes in?
