### ISSUE TITLE
Wrong redirect for GitHub in navbar

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/website#24]
The GitHub link in navbar (top right), redirects to default Docusaurus GitHub. We need to change it to KubeSimplify's.

**Comment by lavakush07** [comment]
Hey Anubhav, I want to take this issue. Can u assign me

**Comment by anubha-v-ardhan** [comment]
Thank you @lavakush07

**Comment by Shivansh-yadav13** [comment]
@lavakush07 @anubha-v-ardhan I think we should also point the Blog link in the footer to the Hashnode page.

**Comment by AvineshTripathi** [comment]
I think this issue would be solved when we get our landing page along with navbar which is work in progress
