### ISSUE TITLE
feat: create kubesimplify Contributors page 

### ISSUE THREAD

**Issue by lavakush07** [kubesimplify/website#25]
Add a contributors  page 
There are different sections like:

1) Link to Hashnode to publish a blog .
2) Details about the team members.
3) Amazing footer.

**Comment by Shivansh-yadav13** [comment]
@lavakush07 can I try working on this, and isn't someone already working on the footer?

**Comment by AvineshTripathi** [comment]
Hey @lavakush07 can you elaborate this more by adding screenshot and other details 

p.s. i believe Ayush is working on footer so maybe that point can be avoided

**Comment by lavakush07** [comment]
![Screenshot 2022-05-01 112945](https://user-images.githubusercontent.com/70131581/166134248-a38f66ed-2bc7-44ce-aa4c-00ee35be8312.png)

**Comment by lavakush07** [comment]
@Shivansh-yadav13 is  working upon this.

**Comment by Shivansh-yadav13** [comment]
@AvineshTripathi from where are we getting the list of contributors? Not sure of that, that's why I have not made a PR.

**Comment by bhavyastar** [comment]
We don't need the contributors' pictures now @Shivansh-yadav13, you can make a pull request without pictures only.

**Comment by Shivansh-yadav13** [comment]
@bhavyastar I'm sorry for not updating, I won't be able to work rn.

**Comment by Shivansh-yadav13** [comment]
@bhavyastar I'm working on it and i'll make the pr.

**Comment by Shivansh-yadav13** [comment]
I think we can close this issue since this page is not needed.
