### ISSUE TITLE
Add a nodejs workflow 

### ISSUE THREAD

**Issue by SuperAayush** [kubesimplify/website#27]
Adding a Nodejs workflow through Github actions will help in testing and building all the PR that are made to the project and also makes it easy for the reviewers to review the PRs.
<img width="1440" alt="Screenshot 2022-05-05 at 12 02 08 AM" src="https://user-images.githubusercontent.com/78820926/166802399-ebd30c3c-a149-49b8-be79-944d7833717e.png">

It checks it for the three versions of node.

**Comment by AnuragThePathak** [comment]
Hi can I work on this issue?

**Comment by AvineshTripathi** [comment]
Sure @AnuragThePathak  you can take this up
