### ISSUE TITLE
Add code of conduct for website

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/website#3]
Every open source project should have a code of coduct that establishes expectation of behaviour from contributors and everyone participating on the project.

KubeSimplify uses [CNCF code of conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

Add a file `code-of-conduct.md` stating above and linking to CNCF's code of conduct

**Comment by Nawaz027** [comment]
I want to work on the issue. Please assign this to me.

**Comment by anubha-v-ardhan** [comment]
@Nawaz027 I don't have requiered privileges to assign issues yet but your comment should be enough. You can start working and open a PR.
Thank you for contributing :)

**Comment by Nawaz027** [comment]
sure, thank you.
