### ISSUE TITLE
Fix base URL

### ISSUE THREAD

**Issue by Shivansh-yadav13** [kubesimplify/website#31]
- rn the url looks like `https://kubesimplify.github.io/website/`
- I think we should change the base url to `/`
- not sure if this would affect the deployment to gh pages since it was changed in #22 
- https://github.com/kubesimplify/website/blob/fcab83456936aa778d3dddb814fea3367dc51d37/docusaurus.config.js#L12

**Comment by anubha-v-ardhan** [comment]
Do we have any specific reason for the change, as the website will use `kubesimplify.com` when finished

**Comment by Shivansh-yadav13** [comment]
@anubha-v-ardhan I was considering this from the docusaurus website.
But if you think it's not required then we can close this issue 🙂
![routing](https://user-images.githubusercontent.com/87603425/167277710-2cd61dfa-e22e-4896-b241-f169c6f88427.png)

**Comment by anubha-v-ardhan** [comment]
Are you sure this won't break the deployment?

**Comment by Shivansh-yadav13** [comment]
@anubha-v-ardhan I don't think it will break the deployment, but @verma-kunal can confirm, since he changed it in #22

**Comment by anubha-v-ardhan** [comment]
Accepting triage for this, we can check the deployment when PR is made for this issue.
@Shivansh-yadav13 Do you wish to work on this?

**Comment by anubha-v-ardhan** [comment]
REF https://github.com/kubesimplify/website/pull/43#discussion_r872937563
