### ISSUE TITLE
fix: change favicon of website

### ISSUE THREAD

**Issue by SuperAayush** [kubesimplify/website#34]
The current favicon is default of Docusaurus which should be replaced by the kubesimplify logo.

**Comment by shaggyyy2002** [comment]
I think we should add the logos into one folder

**Comment by shivam-sharma7** [comment]
I have open a PR for this issue. Can you assign me?

**Comment by shivam-sharma7** [comment]
@SuperAayush can we close this issue, If it has been done.

**Comment by SuperAayush** [comment]
Yes sure, done 👍🏻
