### ISSUE TITLE
Broken link titled Blogs in website

### ISSUE THREAD

**Issue by Deepakktripathy** [kubesimplify/website#42]
### Description

https://kubesimplify.github.io/website/blog
the above link shows "Page Not Found"
![image](https://user-images.githubusercontent.com/79755187/167693550-7c329b12-5a34-4d2c-9a00-3a359af32892.png)

I believe we can fix the link with the following:
**https://kubesimplify.com/**

**Comment by anubha-v-ardhan** [comment]
We're desigining a new footer for the website but sure, we can fix this for now!

**Comment by shivam-sharma7** [comment]
I have open a PR for this issue? can you assign me?

**Comment by AvineshTripathi** [comment]
This issue is solved please close this
