### ISSUE TITLE
Alignment of Homepage is not consistent

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#45]
### Description

With the new merge of the Homepage in PR #33, we can find an inconsistency in the alignment specially for a higher resolution. 

An issue was seen for the following resolution:
Browser: Chrome 101.0 and Firefox 100.0
Screen resolution: 1920x1080
Screen size: 22 inch

### Screenshots

![image](https://media.discordapp.net/attachments/968171151312445470/974994030914043935/unknown.png?width=757&height=426)

## Problem

Currently the `styles.module.css` uses `px` for various sizes and alignment which makes the component not responsive 

## Possible Solution 

We can use `%` instead of `px` to make it responsive or we can use the CSS @media rule. For more info [link](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp)

Any other idea to this problem is always welcome

**Comment by shivam-sharma7** [comment]
How we can run this project localhost?

**Comment by anubha-v-ardhan** [comment]
> How we can run this project localhost?

1. Clone the repository (clone your fork of the repository if you want to contribute)
2. Change directory (`cd <repo name>`) to the cloned repo on your local machine
3. Run `npm install` to start automatically install all the dependencies
4. Run `npm start` to start the local server. You should be automatically redirected to your default browser and site should open.  If not, go to `localhost:3000/website` on your browser

We'll soon have these steps mentioned in detail on CONTRIBUTING page on this repo

**Comment by shivam-sharma7** [comment]
can you assign me?

**Comment by shivam-sharma7** [comment]
- If you want so, I can add these steps in my PR #26

**Comment by AvineshTripathi** [comment]
resolved
