### ISSUE TITLE
[FEATURE] Change the colour of Text

### ISSUE THREAD

**Issue by shaggyyy2002** [kubesimplify/website#47]
### Description

In the homepage when writing something the text is not visible adding SS to make it more clearer.

### Screenshots

Problem:
![](https://cdn.discordapp.com/attachments/966715029326028800/975472858123886732/Screenshot_2022-05-16_at_12.29.59_AM.png)
Solution: 

![](https://cdn.discordapp.com/attachments/966715029326028800/975690766611513405/unknown.png)

**Comment by shivam-sharma7** [comment]
can you assign me? for this issue

**Comment by shaggyyy2002** [comment]
the triage is on waiting check with @anubha-v-ardhan

**Comment by shivam-sharma7** [comment]
@anubha-v-ardhan @saiyam1814
