### ISSUE TITLE
[Bug] <Footer Social Icons are all same and not redirecting>

### ISSUE THREAD

**Issue by Jai-Solania-29** [kubesimplify/website#49]
### Description

Social icons in Footer sections are all same and they are also not getting redirected anywhere.

### Screenshots

![Screenshot (65)](https://user-images.githubusercontent.com/90816300/169761906-5f665d7c-6535-4973-9433-53792d00efcb.png)

**Comment by Jai-Solania-29** [comment]
I want to work on this issue, Please assign this to me.

**Comment by AvineshTripathi** [comment]
@Jai-Solania-29 thank you for raising this issue, you can always start working on this

**Comment by Jai-Solania-29** [comment]
@AvineshTripathi Ok thank you

**Comment by shaggyyy2002** [comment]
Also the icons are of different colour from the one designed.
<img width="908" alt="Screenshot 2022-05-24 at 8 47 35 PM" src="https://user-images.githubusercontent.com/90847875/170072303-4d429430-e801-489d-884e-f2fa3880bb0b.png">

**Comment by Jai-Solania-29** [comment]
@shaggyyy2002 I have already started working on this issue. I'm just waiting for @anubha-v-ardhan to assign it to me, and then I'll go with PR.

**Comment by AvineshTripathi** [comment]
Hey @Jai-Solania-29 you dont need to wait for getting assigned to create the PR if you are done please create one also consider changing the logos as suggested by @shaggyyy2002 

p.s. shaggyyy2002 you can review the PR and suggest changes if something is missing

**Comment by Jai-Solania-29** [comment]
Hey @AvineshTripathi thank you for clearing the confusion .

**Comment by Jai-Solania-29** [comment]
Hey @AvineshTripathi I want to switch this conversation to Voice ! Are you on kubesimplify's discord channel ?
As I have some queries which would be easier to clear on voice.

**Comment by AvineshTripathi** [comment]
You can ping me @Avinesh

**Comment by anubha-v-ardhan** [comment]
> You can ping me @Avinesh

Hey, we should avoid writing something with "@" on GitHub (or any platform) if you don't really mean to tag someone as it will ping other people if the username matches and give them an unnecessary notification!

**Comment by AvineshTripathi** [comment]
Oh i missed the ` sign thanks @anubha-v-ardhan for notifying

**Comment by Jai-Solania-29** [comment]
@AvineshTripathi  Actually I wanted the Figma file so that I can give the finishing touch to the footer easily. As its really hard to find the exact font given in the screenshot provided by shaggyyy.

**Comment by Avinesh** [comment]
> > You can ping me @Avinesh
> 
> Hey, we should avoid writing something with "@" on GitHub (or any platform) if we don't really mean to tag someone as it will ping other people if the GitHub username matches giving them an unnecessary notification!

I concur :)

**Comment by AvineshTripathi** [comment]
I apologise profusely. I forgot to include the sign in the comment. I hope that wouldn't interrupt you.

**Comment by Jai-Solania-29** [comment]
@AvineshTripathi what should I do?

> @AvineshTripathi Actually I wanted the Figma file so that I can give the finishing touch to the footer easily. As its really hard to find the exact font given in the screenshot provided by shaggyyy.

**Comment by Santosh1176** [comment]
There is also a minor issue in footer. In copyright section, it's still showing 'my website, inc'. This should be changed to 'Kubesimplify'.
