### ISSUE TITLE
[FEATURE] Add CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by kranurag7** [kubesimplify/website#58]
### Description

- Add the contributing.md file explaining how to clone the repo and get started with contributing. 
- What are the requirements one should have before cloning the repo? 
- Mention how to propose a feature request? 
- How to create a pull request?

**Comment by Santosh1176** [comment]
Can I work on this?

**Comment by kranurag7** [comment]
Sure @Santosh1176 You can start working on this.

**Comment by NitishKumar06** [comment]
Hey, I'd like to work on this issue. 
Please let me know.
