### ISSUE TITLE
[FEATURE] Create remaining part of the ambassador page

### ISSUE THREAD

**Issue by mayankkuamr001** [kubesimplify/website#63]
### Description

The following components need to be created.
-  application component
- FAQs

### Screenshots

![image](https://user-images.githubusercontent.com/66107976/171393243-c4190207-6e55-4d12-a2fe-e96fc50c8ff2.png)

![image](https://user-images.githubusercontent.com/66107976/171393264-d2ad745c-62ce-43b1-b21a-77be3eac8872.png)

**Comment by mayankkuamr001** [comment]
Please assign this issue to me as I have created the half of ambassador page.

**Comment by AvineshTripathi** [comment]
You can start working on this even without getting assigned
