### ISSUE TITLE
[FEATURE] Add Some Padding in Newsletter Button in Nav bar

### ISSUE THREAD

**Issue by bishal7679** [kubesimplify/website#67]
### Description

Left and right padding have to be added because the newsletter button not looking so cool for that and also cursor to be changed.

### Screenshots

![Screenshot (101)](https://user-images.githubusercontent.com/70086051/171913953-516dac03-1754-4650-8f94-b08ad33f39db.png)

![Screenshot (100)](https://user-images.githubusercontent.com/70086051/171913691-847fb51c-c56e-421b-9ca5-cc1fb47b24ba.png)

**Comment by AvineshTripathi** [comment]
I accept this issue but wait for the PR till issue gets the label `triage-accepted`. It is a good practice

**Comment by bishal7679** [comment]
@AvineshTripathi ok no problem

**Comment by bishal7679** [comment]
@anubha-v-ardhan I have made a PR on this. Can you merge this?

**Comment by bishal7679** [comment]
This issue is fixed by PR #74 . So I have closed the PR #68 
@anubha-v-ardhan @AvineshTripathi
