### ISSUE TITLE
[CLEANUP] Delete unused default Docusaurus images

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubesimplify/website#69]
### What would you like to share?

We don't need the default Docusaurus images present in [static/img/](https://github.com/kubesimplify/website/tree/main/static/img). It would be better if we delete them to clean things up.

The images we aren't using are:

- [docusaurus.png](https://github.com/kubesimplify/website/blob/main/static/img/docusaurus.png)
- [logo.svg](https://github.com/kubesimplify/website/blob/main/static/img/logo.svg)
- [undraw_docusaurus_mountain.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_mountain.svg)
- [undraw_docusaurus_react.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_react.svg)
- [undraw_docusaurus_tree.svg](https://github.com/kubesimplify/website/blob/main/static/img/undraw_docusaurus_tree.svg)

**Comment by code-hyker** [comment]
Should the above mentioned images be deleted?

**Comment by Abhishekvrt** [comment]
If this issue is fixed then please close this PR @code-hyker 

hey @anubha-v-ardhan can you tell me about the status of this pr

**Comment by Utpalkant6204** [comment]
Remaining 4 images also want to be deleted? @anubha-v-ardhan

**Comment by Utpalkant6204** [comment]
hey @anubha-v-ardhan , remaining 4 images also wanted to be deleted? If yes, I would like to work on it.

**Comment by code-hyker** [comment]
@Utpalkant6204 we are already working on it

**Comment by code-hyker** [comment]
Approve the pull requests to make updates ! They have been pending for a long time.

**Comment by bishal7679** [comment]
@code-hyker please make all changes in one PR.

**Comment by code-hyker** [comment]
So should I close all of them now?

**Comment by bishal7679** [comment]
Yeap!

**Comment by bishal7679** [comment]
@AvineshTripathi now you can merge these two PR.
