### ISSUE TITLE
[FEATURE] Add hover effect on the buttons of navigation bar

### ISSUE THREAD

**Issue by bishal7679** [kubesimplify/website#75]
### Description

Hover effect will be added on the all nav bar buttons.

### Screenshots

https://user-images.githubusercontent.com/70086051/172016865-d67ea86a-0c64-4fae-86c4-1c4c988fdd52.mp4

**Comment by bishal7679** [comment]
@samjn08 What's your suggestion.
Can I add this hover effect on the nav bar buttons?

**Comment by Nawaz027** [comment]
Hey folks, if no one is working on the issue, can I grab it?

**Comment by bishal7679** [comment]
@Nawaz027 Thanks for showing interest
Actually I am waiting for @samjn08 his opinion then only I can make PR for this.

**Comment by bishal7679** [comment]
@AvineshTripathi @anubha-v-ardhan 
Can I add it?

**Comment by bishal7679** [comment]
@AvineshTripathi @verma-kunal 
Can I add this?

**Comment by AvineshTripathi** [comment]
I was too waiting for JJ's opinion, LGTM

**Comment by bishal7679** [comment]
@AvineshTripathi okay. Can I start working then?
