### ISSUE TITLE
[Bug] Components are not functional on the HomePage

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#78]
### Description

- The `Subscribe` button and the `Email Address` text field is not functional
- For both the cards below i.e. the `Blog content` and `Youtube content` the button is functional but there is no button effect/animation on clicking

### Screenshots

![2022-06-09_02-23](https://user-images.githubusercontent.com/73980067/172715022-37714a36-a308-423c-af41-f38e83a99e11.png)
![2022-06-09_02-16](https://user-images.githubusercontent.com/73980067/172715055-9819ce43-d9de-4867-a96f-0188579722e4.png)

### Additional information

**For maintainers**
We can add `good-first-issue` to this issue

**Comment by AvineshTripathi** [comment]
You can work on this without `assign`

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
**Now, What should I do?**
